export const NewsActionTypes = {
  GET_NEWS_START: "GET_NEWS_START",
  GET_NEWS_SUCCESS: "GET_NEWS_SUCCESS",
  GET_NEWS_FAILURE: "GET_NEWS_FAILURE",
  CRUD_NEWS_STATUS_RESET: "CRUD_NEWS_STATUS_RESET",
};
